<?php

namespace RPZ\DiscussionBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
  public function getLastArticles($date_from, $username) {
    $results = $this
      ->createQueryBuilder('article')
      ->where('article.date >= :date_from')
      ->setParameter('date_from', $date_from)
      ->andWhere('article.author != :username')
      ->setParameter('username', $username)
      ->getQuery()
      ->getResult()
    ;
    return $results;
  }
}
