<?php

namespace RPZ\DiscussionBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
  public function whereArticle($id) {
    return $this->createQueryBuilder('e')
        ->innerJoin('e.article', 'i')
        ->where('i.id = :id')
        ->setParameter('id', $id)
        ->getQuery()
        ->getResult()
    ;
  }
  public function getLastComments($date_from, $username) {
    $results = $this
      ->createQueryBuilder('comment')
      ->leftJoin('comment.article', 'article')
      ->addSelect('article')
      ->where('article.type = \'article\'')
      ->andWhere('comment.date >= :date_from')
      ->setParameter('date_from', $date_from)
      ->andWhere('comment.author != :username')
      ->setParameter('username', $username)
      ->getQuery()
      ->getResult()
    ;
    return $results;
  }
  public function getArticleIdFromComments($comments){
    $articleIds = [];
    foreach($comments as $comment){
      $articleIds[] = $comment->getArticle()->getId();
    }
    return array_unique($articleIds);
  }
}
