<?php

namespace RPZ\DiscussionBundle\Repository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
  public function lastActivity() {
    return $this->createQueryBuilder('log')
        ->select('log.username, MAX(log.date) as date')
        ->groupBy('log.username')
        ->orderBy('date', 'desc')
        ->getQuery()
        ->getResult()
    ;
  }
  public function lastConnexionDate($username) {
    $current_date = new \DateTime();
    $current_date->modify('-30 minutes');
    $results =  $this->createQueryBuilder('log')
        ->select('MAX(log.date) as date')
        ->where('log.username = :username')
        ->andWhere('log.date < :current_date')
        ->setParameter('username', $username)
        ->setParameter('current_date', $current_date)
        ->getQuery()
        ->getResult()
    ;
    return $results[0]['date'];
  }
}
