<?php

namespace RPZ\DiscussionBundle\Repository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
  public function lastActivity() {
    return $this->createQueryBuilder('log')
        ->select('log.username, MAX(log.date) as date')
        ->groupBy('log.username')
        ->orderBy('date', 'desc')
        ->getQuery()
        ->getResult()
    ;
  }
}
